pipelines:
  default:
    - stage: &build_test
        name: Build and Unit Tests
        steps:
          - step:
              name: Build
              image: golang:1.22-alpine
              script:
                - apk add --no-cache make gcc musl-dev
                - make all
          - step:
              name: Unit Tests
              image: golang:1.22-alpine
              script:
                - apk add --no-cache make gcc musl-dev
                - make test
        trigger: automatic
  branches:
    main:
      - stage: *build_test
      - stage:
          steps:
            - step:
                name: Build and deliver docker image
                image: docker:latest
                services:
                  - docker
                script:
                  - echo "${DOCKER_REGISTRY_PASSWORD}" | docker login -u "${DOCKER_REGISTRY_USERNAME}" "${DOCKER_REGISTRY_URL}" --password-stdin
                  - export DOCKER_BUILDKIT=0
                  - export IMAGE="${DOCKER_REGISTRY_URL}/arnal/chaos-monkey"
                  - export TAG="latest"
                  - docker build -t "${IMAGE}:${TAG}" -f Dockerfile .
                  - docker push "${IMAGE}:${TAG}"
          trigger: automatic
