pipelines:
  default:
    - stage: &build_test
        name: Build and Unit Tests
        steps:
          - step:
              name: Build
              image: golang:1.22-alpine
              script:
                - apk add --no-cache make gcc musl-dev
                - make all
          - step:
              name: Unit Tests
              image: golang:1.22-alpine
              script:
                - apk add --no-cache make gcc musl-dev
                - make test
        trigger: automatic
    - stage: &intg_test
        name: Integration Test
        steps:
          - step:
              name: Terraform tests
              image: hashicorp/terraform:1.8
              script:
                - apk add --no-cache make gcc musl-dev go docker-cli kubectl
                - go install sigs.k8s.io/kind@v0.23.0
                - export PATH=$PATH:$(go env GOPATH)/bin
                - terraform init
                - make cluster-test
                - kubectl get ns | grep target
                - kubectl get ns | grep chaosmonkey
                - kubectl -n chaosmonkey get pods | grep chaos-monkey
                - kubectl -n target get deployments | grep nginx
                - kubectl -n target get cmc | grep chaosmonkey-nginx
                - kubectl -n target get events | grep ChaosMonkey
                - make clean
  branches:
    main:
      - stage: *build_test
      - stage: *intg_test
      - stage:
          steps:
            - step:
                name: Build and deliver docker image
                image: docker:latest
                services:
                  - docker
                script:
                  - echo "${DOCKER_REGISTRY_PASSWORD}" | docker login -u "${DOCKER_REGISTRY_USERNAME}" "${DOCKER_REGISTRY_URL}" --password-stdin
                  - export DOCKER_BUILDKIT=0
                  - export IMAGE="${DOCKER_REGISTRY_URL}/arnal/chaos-monkey"
                  - export TAG="latest"
                  - docker build -t "${IMAGE}:${TAG}" -f Dockerfile .
                  - docker push "${IMAGE}:${TAG}"
          trigger: automatic
