// Generated code, do not touch

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/massix/chaos-monkey/internal/apis/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeChaosMonkeyConfigurations implements ChaosMonkeyConfigurationInterface
type FakeChaosMonkeyConfigurations struct {
	Fake *FakeChaosMonkeyConfigurationV1alpha1
	ns   string
}

var chaosmonkeyconfigurationsResource = v1alpha1.SchemeGroupVersion.WithResource("chaosmonkeyconfigurations")

var chaosmonkeyconfigurationsKind = v1alpha1.SchemeGroupVersion.WithKind("ChaosMonkeyConfiguration")

// Get takes name of the chaosMonkeyConfiguration, and returns the corresponding chaosMonkeyConfiguration object, and an error if there is any.
func (c *FakeChaosMonkeyConfigurations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ChaosMonkeyConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(chaosmonkeyconfigurationsResource, c.ns, name), &v1alpha1.ChaosMonkeyConfiguration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChaosMonkeyConfiguration), err
}

// List takes label and field selectors, and returns the list of ChaosMonkeyConfigurations that match those selectors.
func (c *FakeChaosMonkeyConfigurations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ChaosMonkeyConfigurationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(chaosmonkeyconfigurationsResource, chaosmonkeyconfigurationsKind, c.ns, opts), &v1alpha1.ChaosMonkeyConfigurationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ChaosMonkeyConfigurationList{ListMeta: obj.(*v1alpha1.ChaosMonkeyConfigurationList).ListMeta}
	for _, item := range obj.(*v1alpha1.ChaosMonkeyConfigurationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested chaosMonkeyConfigurations.
func (c *FakeChaosMonkeyConfigurations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(chaosmonkeyconfigurationsResource, c.ns, opts))

}

// Create takes the representation of a chaosMonkeyConfiguration and creates it.  Returns the server's representation of the chaosMonkeyConfiguration, and an error, if there is any.
func (c *FakeChaosMonkeyConfigurations) Create(ctx context.Context, chaosMonkeyConfiguration *v1alpha1.ChaosMonkeyConfiguration, opts v1.CreateOptions) (result *v1alpha1.ChaosMonkeyConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(chaosmonkeyconfigurationsResource, c.ns, chaosMonkeyConfiguration), &v1alpha1.ChaosMonkeyConfiguration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChaosMonkeyConfiguration), err
}

// Update takes the representation of a chaosMonkeyConfiguration and updates it. Returns the server's representation of the chaosMonkeyConfiguration, and an error, if there is any.
func (c *FakeChaosMonkeyConfigurations) Update(ctx context.Context, chaosMonkeyConfiguration *v1alpha1.ChaosMonkeyConfiguration, opts v1.UpdateOptions) (result *v1alpha1.ChaosMonkeyConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(chaosmonkeyconfigurationsResource, c.ns, chaosMonkeyConfiguration), &v1alpha1.ChaosMonkeyConfiguration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChaosMonkeyConfiguration), err
}

// Delete takes name of the chaosMonkeyConfiguration and deletes it. Returns an error if one occurs.
func (c *FakeChaosMonkeyConfigurations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(chaosmonkeyconfigurationsResource, c.ns, name, opts), &v1alpha1.ChaosMonkeyConfiguration{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeChaosMonkeyConfigurations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(chaosmonkeyconfigurationsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ChaosMonkeyConfigurationList{})
	return err
}

// Patch applies the patch and returns the patched chaosMonkeyConfiguration.
func (c *FakeChaosMonkeyConfigurations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ChaosMonkeyConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(chaosmonkeyconfigurationsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ChaosMonkeyConfiguration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChaosMonkeyConfiguration), err
}
