// Generated code, do not touch

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/massix/chaos-monkey/internal/apis/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// ChaosMonkeyConfigurations returns a ChaosMonkeyConfigurationInformer.
	ChaosMonkeyConfigurations() ChaosMonkeyConfigurationInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// ChaosMonkeyConfigurations returns a ChaosMonkeyConfigurationInformer.
func (v *version) ChaosMonkeyConfigurations() ChaosMonkeyConfigurationInformer {
	return &chaosMonkeyConfigurationInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
