// Generated code, do not touch

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ChaosMonkeyConfigurationListerExpansion allows custom methods to be added to
// ChaosMonkeyConfigurationLister.
type ChaosMonkeyConfigurationListerExpansion interface{}

// ChaosMonkeyConfigurationNamespaceListerExpansion allows custom methods to be added to
// ChaosMonkeyConfigurationNamespaceLister.
type ChaosMonkeyConfigurationNamespaceListerExpansion interface{}
