{
 "title": "Chaos Monkey",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus Data Source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance of ChaosMonkey",
    "query": {
     "query": "label_values(chaos_monkey_nswatcher_events,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Basic Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Namespaces Monitored",
   "type": "gauge",
   "description": "Current number of namespaces being monitored",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chaos_monkey_nswatcher_cmc_active{instance=\"$instance\"}",
     "legendFormat": "{{namespace}} ({{behavior}})"
    }
   ]
  },
  {
   "title": "Active PodWatchers",
   "type": "bargauge",
   "description": "Currently active podwatchers per namespace",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chaos_monkey_crdwatcher_pw_active{instance=\"$instance\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Active DeploymentWatchers",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chaos_monkey_crdwatcher_dw_active{instance=\"$instance\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Restarts per component",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(namespace) (chaos_monkey_podwatcher_restarts{instance=\"$instance\"})",
     "legendFormat": "PW: {{namespace}}"
    },
    {
     "expr": "sum by(namespace) (chaos_monkey_crdwatcher_restarts{instance=\"$instance\"})",
     "legendFormat": "CRD: {{namespace}}"
    },
    {
     "expr": "sum by(root_namespace) (chaos_monkey_nswatcher_restarts{instance=\"$instance\"})",
     "legendFormat": "NS: {{root_namespace}}"
    }
   ]
  },
  {
   "title": "Total Events Processed",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "chaos_monkey_nswatcher_events{event_type=\"add\",instance=\"$instance\"}",
     "legendFormat": "NS: Add"
    },
    {
     "expr": "chaos_monkey_nswatcher_events{event_type=\"delete\",instance=\"$instance\"}",
     "legendFormat": "NS: Delete"
    },
    {
     "expr": "chaos_monkey_nswatcher_events{event_type=\"modify\",instance=\"$instance\"}",
     "legendFormat": "NS: Modify"
    },
    {
     "expr": "sum by(event_type) (chaos_monkey_crdwatcher_events{event_type=\"add\",instance=\"$instance\"})",
     "legendFormat": "CRD: Add"
    },
    {
     "expr": "sum by(event_type) (chaos_monkey_crdwatcher_events{event_type=\"delete\",instance=\"$instance\"})",
     "legendFormat": "CRD: Delete"
    },
    {
     "expr": "sum by(event_type) (chaos_monkey_crdwatcher_events{event_type=\"modify\",instance=\"$instance\"})",
     "legendFormat": "CRD: Modify"
    }
   ]
  },
  {
   "title": "Time spent treating events in µs for CRD Watchers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum by (namespace) (histogram_quantile(0.5, chaos_monkey_crdwatcher_event_duration_bucket{instance=\"$instance\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time spent treating events in µs for NS Watchers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, chaos_monkey_nswatcher_event_duration_bucket{instance=\"$instance\"})",
     "legendFormat": "{{root_namespace}}"
    }
   ]
  },
  { "title": "PodWatchers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Pods killed per minute",
   "type": "timeseries",
   "description": "Number of pods killed per namespace",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by(namespace, label_selector) (rate(chaos_monkey_podwatcher_pods_killed{instance=\"$instance\"}[10m]) * 60)",
     "legendFormat": "namespace {{namespace}}, selector {{label_selector}}"
    }
   ]
  },
  {
   "title": "Currently targeted pods",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(label_selector, namespace) (chaos_monkey_podwatcher_pods_active{instance=\"$instance\"})",
     "legendFormat": "{{namespace}} {{label_selector}}"
    }
   ]
  },
  {
   "title": "Pods added per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum by(namespace, label_selector) (rate(chaos_monkey_podwatcher_pods_added{instance=\"$instance\"}[15m]) * 60)",
     "legendFormat": "{{namespace}} - {{label_selector}}"
    }
   ]
  },
  {
   "title": "Pods removed per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum by (namespace, label_selector) (rate(chaos_monkey_podwatcher_pods_removed{instance=\"$instance\"}[15m]) * 60)",
     "legendFormat": "{{namespace}} - {{label_selector}}"
    }
   ]
  },
  { "title": "DeploymentWatchers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Number of deployments scaled per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum by (deployment, namespace) (rate(chaos_monkey_deploymentwatcher_deployments_rescaled{instance=\"$instance\"}[15m]) * 60)",
     "legendFormat": "{{namespace}} - {{deployment}}"
    }
   ]
  },
  {
   "title": "Average values for rescale",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 42 },
   "targets": [
    {
     "expr": "avg by (namespace,deployment) (chaos_monkey_deploymentwatcher_last_scale{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last used scale for DeploymentWatcher",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chaos_monkey_deploymentwatcher_last_scale{instance=\"$instance\"}",
     "legendFormat": "{{namespace}} - {{deployment}}"
    }
   ]
  }
 ]
}