//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Generated code, do not touch

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChaosMonkeyConfiguration) DeepCopyInto(out *ChaosMonkeyConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChaosMonkeyConfiguration.
func (in *ChaosMonkeyConfiguration) DeepCopy() *ChaosMonkeyConfiguration {
	if in == nil {
		return nil
	}
	out := new(ChaosMonkeyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChaosMonkeyConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChaosMonkeyConfigurationList) DeepCopyInto(out *ChaosMonkeyConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ChaosMonkeyConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChaosMonkeyConfigurationList.
func (in *ChaosMonkeyConfigurationList) DeepCopy() *ChaosMonkeyConfigurationList {
	if in == nil {
		return nil
	}
	out := new(ChaosMonkeyConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChaosMonkeyConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChaosMonkeyConfigurationSpec) DeepCopyInto(out *ChaosMonkeyConfigurationSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChaosMonkeyConfigurationSpec.
func (in *ChaosMonkeyConfigurationSpec) DeepCopy() *ChaosMonkeyConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(ChaosMonkeyConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChaosMonkeyConfigurationStatus) DeepCopyInto(out *ChaosMonkeyConfigurationStatus) {
	*out = *in
	if in.LastExecution != nil {
		in, out := &in.LastExecution, &out.LastExecution
		*out = (*in).DeepCopy()
	}
	if in.LastKnownReplicas != nil {
		in, out := &in.LastKnownReplicas, &out.LastKnownReplicas
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChaosMonkeyConfigurationStatus.
func (in *ChaosMonkeyConfigurationStatus) DeepCopy() *ChaosMonkeyConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(ChaosMonkeyConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}
