apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: chaosmonkeyconfigurations.cm.massix.github.io
spec:
  group: cm.massix.github.io
  scope: Namespaced
  names:
    plural: chaosmonkeyconfigurations
    singular: chaosmonkeyconfiguration
    kind: ChaosMonkeyConfiguration
    shortNames:
      - cmc
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-validations:
                - rule: "self.minReplicas <= self.maxReplicas"
                  message: "minReplicas must be less than or equal to maxReplicas"
                - rule: "self.deploymentName != ''"
                  message: "deploymentName must not be empty"
              properties:
                enabled:
                  type: boolean
                  description: Whether or not the ChaosMonkey is enabled for this namespace
                  default: true
                minReplicas:
                  type: integer
                  description: Minimum number of replicas
                  minimum: 0
                  default: 0
                maxReplicas:
                  type: integer
                  description: Maximum number of replicas
                  maximum: 10
                  default: 5
                deploymentName:
                  type: string
                  description: Deployment to which this CRD is associated to
                podMode:
                  type: boolean
                  description: |
                    Set this to true to kill random pods of the deployment instead of modifying
                    the scale properties of the original deployment (this is a better solution if
                    you have HPAs)
                  default: true
                timeout:
                  type: string
                  description: Timeout for the chaosmonkey
                  default: 30s
            status:
              type: object
              properties:
                accepted:
                  type: boolean
                  description: Whether or not this configuration has been accepted by the CRD watcher
                lastExecution:
                  type: string
                  description: Timestamp of the last execution
                lastKnownReplicas:
                  type: integer
                  description: Last known number of replicas
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Enabled
          type: boolean
          jsonPath: .spec.enabled
        - name: Deployment
          type: string
          jsonPath: .spec.deploymentName
        - name: Min Replicas
          type: integer
          jsonPath: .spec.minReplicas
        - name: Max Replicas
          type: integer
          jsonPath: .spec.maxReplicas
        - name: Disrupt Pods
          type: boolean
          jsonPath: .spec.podMode
