name: CI
on: [push]
jobs:
  build:
    name: Build and Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - run: make all
      - run: make test
  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.5"
      - uses: azure/setup-kubectl@v3
        with:
          version: "v1.30.1"
      - uses: engineerd/setup-kind@v0.5.0
        with:
          skipClusterCreation: true
      - run: terraform init
        name: Initialize Terraform
      - run: |
          make cluster-test
          sleep 10
          ./tests/kubetest.sh
        name: End to end tests
      - run: make clean
        name: Cleanup
