name: Check commits
on: [pull_request]
jobs:
  cogcheck:
    name: Check commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: cocogitto/cocogitto-action@v3
        with:
          check-latest-tag-only: true
