name: Deploy on DockerHub
on:
  push:
    tags: ['v*']
permissions:
  contents: write
  pull-requests: read
  checks: read
jobs:
  deploy:
    name: Deploy on DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - run: |
          export IMAGE="${{ secrets.DOCKER_REGISTRY_USERNAME }}/$(make image-name)"
          make docker
          docker push "${IMAGE}:$(make image-tag)"
          docker tag "${IMAGE}:$(make image-tag)" "${IMAGE}:latest"
          docker push "${IMAGE}:latest"
  release:
    name: Generate Changelog
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use cocogitto to generate CHANGELOG.md
        uses: cocogitto/cocogitto-action@v3
        with:
          release: true
      - uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          generate_release_notes: true
          make_latest: "true"
          draft: false
      - name: Commit back report
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "github-actions[bot]"
          git push
