// Generated code, do not touch

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/massix/chaos-monkey/internal/apis/clientset/versioned/typed/apis/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeChaosMonkeyConfigurationV1 struct {
	*testing.Fake
}

func (c *FakeChaosMonkeyConfigurationV1) ChaosMonkeyConfigurations(namespace string) v1.ChaosMonkeyConfigurationInterface {
	return &FakeChaosMonkeyConfigurations{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeChaosMonkeyConfigurationV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
